name: SBOM

on:
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements.lock
            engines/**/requirements*.txt
            engines/**/pyproject.toml
            src/ma_config/pyproject.toml
            shared/pyproject.toml
      - name: Install cyclonedx
        run: python -m pip install cyclonedx-bom
      - name: Generate SBOM
        run: |
          PYTHONPATH=. python -m cyclonedx_py --format json --outfile docs/sbom/sbom.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: docs/sbom/sbom.json
